Update to swift 3
fs/ios-base-swift pull request #64
Opened 2016-10-25 09:54 UTC by NikitaAsabin

Update to swift 3.

2016-10-25 10:03 UTC, kruperfone requested changes

2016-10-25 10:03 UTC, NikolaevSergey commented on Swift-Base/DeepLink.swift
> +    fileprivate override init()
Думаю лучше использовать обычный private

2016-10-25 10:03 UTC, NikolaevSergey commented on Swift-Base/Constants.swift
> +        fileprivate static let Prefix = "FSDeviceToken"
Надо определиться, почему мы хотим скрыть этот параметр и от кого
Я ставил здесь private чтобы он не попадал в автокомплит
По сути здесь должен быть обычный private, я думаю

2016-10-25 10:22 UTC, NikitaAsabin commented on Swift-Base/Constants.swift
> +        fileprivate static let Prefix = "FSDeviceToken"
Да, тут я с тобой согласен, здесь лучше оставить private

2016-10-25 10:29 UTC, NikitaAsabin commented on Swift-Base/DeepLink.swift
> +    fileprivate override init()
Обычный private не позволит вызвать super.init() в наследуемом классе

2016-10-25 16:23 UTC, ZalyalovIldar approved these changes

2016-10-25 16:26 UTC, EllinaKuznetcova approved these changes

2016-10-31 08:39 UTC, merged

2016-10-31 08:44 UTC, NikitaAsabin commented
resolve #65